services:
  postgres:
    image: postgres:latest
    container_name: postgresdb-1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    ports:
      - '5432:5432'

